# Generated by Django 4.2.25 on 2025-10-24 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('error_rate', 'High Error Rate'), ('slow_response', 'Slow Response Time'), ('rate_limit', 'Rate Limit Exceeded')], max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('state', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved')], default='triggered', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('error_rate', 'High Error Rate'), ('slow_response', 'Slow Response Time'), ('rate_limit', 'Rate Limit Exceeded')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('threshold', models.FloatField()),
                ('window_minutes', models.IntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('duration', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_adb931_idx'), models.Index(fields=['status_code'], name='monitoring__status__38f175_idx'), models.Index(fields=['duration'], name='monitoring__duratio_b09580_idx')],
            },
        ),
    ]
